services:
  app:
    image: ghcr.io/heymesson-az/sistema-web-de-livros:latest

    restart: unless-stopped

    ports:
      - "80:80"

    env_file:
      - .env

    environment:
      APP_ENV: production

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.4

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: db_livros
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:
