name: Implantar na Produção (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Confira o código
        uses: actions/checkout@v4

      - name: Implantação do executável via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/apps/Sistema-Web-de-Livros
            
            # 1. Baixar as novidades do Git
            git pull origin main
            
            # 2. Reconstruir e subir o container Docker
            docker compose up -d --build
            
            # 3. Executar as migrações e otimizações dentro do container em execução
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache
            docker compose exec -T app php artisan view:cache