name: Implantar na Produção

on:
  push:
    branches:
      - main # ou 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Confira o código
        uses: actions/checkout@v4

      - name: Implantação do executável via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/apps/Sistema-Web-de-Livros
            php artisan down --retry=60
            git pull origin main
            composer install --no-dev --optimize-autoloader --no-interaction
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up
